# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data01', '0004_remove_pd1_where'),
    ]

    operations = [
        migrations.AddField(
            model_name='pd1',
            name='where',
            field=models.CharField(default='default where', max_length=20),
        ),
    ]
