# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data01', '0005_pd1_where'),
    ]

    operations = [
        migrations.CreateModel(
            name='pd1_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default title', max_length=20)),
                ('date', models.DateField(default='default date')),
                ('starttime', models.TimeField(default='default time')),
                ('endtime', models.TimeField(default='default time')),
                ('theme', models.TextField(default='default theme')),
                ('who', models.CharField(default='default who', max_length=20)),
                ('where', models.CharField(default='default where', max_length=20)),
            ],
        ),
    ]
