# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data01', '0006_pd1_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd1_time',
            name='date',
            field=models.DateTimeField(default='default date'),
        ),
        migrations.AlterField(
            model_name='pd1_time',
            name='endtime',
            field=models.DateTimeField(default='default time'),
        ),
        migrations.AlterField(
            model_name='pd1_time',
            name='starttime',
            field=models.DateTimeField(default='default time'),
        ),
    ]
