# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data01', '0009_auto_20171115_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='pd2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('endtime', models.TimeField(blank=True, null=True)),
                ('theme', models.TextField(blank=True, null=True)),
                ('who', models.CharField(blank=True, max_length=20, null=True)),
                ('where', models.CharField(blank=True, max_length=20, null=True)),
                ('addurl', models.URLField(blank=True, max_length=100, null=True)),
                ('imgurl', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='pd1',
        ),
        migrations.DeleteModel(
            name='PosterData',
        ),
    ]
